version: '3.9'

services:
  # --- Servicio Web (PHP + Apache)
  web:
    build: .
    container_name: mini-framework-web
    ports:
      - "8080:80"
    volumes:
      - ./mini-framework:/var/www/html/mini-framework
    depends_on:
      - db
    networks:
      - mini-net

  # --- Servicio de Base de Datos (MariaDB)
  db:
    image: mariadb:latest
    container_name: mini-framework-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mini_framework_db
      MYSQL_USER: proyutu
      MYSQL_PASSWORD: 12345678
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mini-net

# --- Redes y vol√∫menes
networks:
  mini-net:

volumes:
  db_data:

